Adding testing for TOP N = 100
Tony-X/search-benchmark-game pull request #52
Opened 2023-08-23 11:23 UTC by slow-J

While I am making changes to the DoQuery class, I'm also enabling dynamic pruning immediately.

![image](https://github.com/Tony-X/search-benchmark-game/assets/32519034/c0341999-bb97-45a9-9b01-e5ac7ee940c6)

Closes https://github.com/Tony-X/search-benchmark-game/issues/2, https://github.com/Tony-X/search-benchmark-game/issues/41.

---

TODO: 
* upload new `web/build/results.json`, pending re-run of benchmark.
* Is the Lucene DoQuery respecting the TotalHitsThreshold? See picture above, why is the doc count not 100 like Tantivy?

2023-08-23 13:20 UTC, slow-J commented
The documentation: https://github.com/Tony-X/search-benchmark-game/blob/luceneutil/CONTRIBUTE.md#serve states that `TOP10 computes the top-K elements. Just outputs "1"`, therefore the result doc count doesn't matter.  The Tantivy `do_query.rs` is returning N. The Lucene `getTotalHits` returns `The total number of documents that matched this query`. `topDocsSize` is protected so we cannot access this.

We can therefore:
* Leave as is and ignore the value? (result will then contain a mismatch between Tantivy and Lucene)
* Hardcode Lucene to return N?
* Hardcode both engines to return 1?

2023-08-23 13:28 UTC, slow-J commented
Attaching results.json (same as `web/build/results.json` in commit)

[results.json.zip](https://github.com/Tony-X/search-benchmark-game/files/12419669/results.json.zip)

2023-08-30 18:34 UTC, Tony-X commented
So both engine can't provide accurate counts when skipping is enabled. Lucene provides a lower bound and tantivy just implicitly says "I have at least the number of hits returned from TopDocs". 

Your benchmarks result should be valid -- in issue https://github.com/Tony-X/search-benchmark-game/issues/4 I did the overlap test with skipping enabled. The overlap numbers are quite high

2023-08-30 18:48 UTC, Tony-X requested changes

2023-08-30 18:48 UTC, Tony-X commented on engines/lucene-9.7.0/src/main/java/DoQuery.java
> +                            // Collector enabled manually to enable dynamic pruning immediately.
Good opportunity to refactor

2023-08-30 18:48 UTC, Tony-X commented on engines/tantivy-0.20/src/bin/do_query.rs
> +            }
Similarly, we could refactor this together with TOP_10

2023-09-05 18:44 UTC, slow-J commented on engines/lucene-9.7.0/src/main/java/DoQuery.java
> +                            // Collector enabled manually to enable dynamic pruning immediately.
Good suggestion, done in newest commit.

2023-09-05 20:28 UTC, Tony-X approved these changes

2023-09-05 20:29 UTC, merged